apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  db-url: jdbc:mysql://database:3306/nagp
  db-database: nagp
  db-user: k8sapp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts-configmap
data:
  init.sql: |
    CREATE TABLE your_table (
      id INT AUTO_INCREMENT PRIMARY KEY,
      column1 VARCHAR(255),
      column2 VARCHAR(255),
      column3 VARCHAR(255)
    );

    INSERT INTO your_table (column1, column2, column3) VALUES ('Ravi', 'Maths', '97');
    INSERT INTO your_table (column1, column2, column3) VALUES ('Teaja', 'Maths', '98');
    -- Add more SQL statements as needed