apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /d/nagp/mysqldata